gnuplot -e "set terminal png size 1280,720; set output 'graphs/results1_all.png'; plot 'results1' using 2:8 title 'simple' with linespoints, '' using 2:10 title 'optimised\_berk' with linespoints, '' using 2:12 title 'optimised\_yunus' with linespoints, '' using 2:14 title 'optimised\_otto\_prefetched' with linespoints, '' using 2:16 title 'optimised\_yunus\_threaded' with linespoints, '' using 2:18 title 'optimised\_berk\_openmp' with linespoints"
gnuplot -e "set terminal png size 1280,720; set output 'graphs/results1_optimised.png'; plot 'results1' using 2:10 title 'optimised\_berk' with linespoints, '' using 2:12 title 'optimised\_yunus' with linespoints, '' using 2:14 title 'optimised\_otto\_prefetched' with linespoints, '' using 2:16 title 'optimised\_yunus\_threaded' with linespoints, '' using 2:18 title 'optimised\_berk\_openmp' with linespoints"

gnuplot -e "set terminal png size 1280,720; set output 'graphs/results2_all.png'; plot 'results2' using 2:8 title 'simple' with linespoints, '' using 2:10 title 'optimised\_berk' with linespoints, '' using 2:12 title 'optimised\_yunus' with linespoints, '' using 2:14 title 'optimised\_otto\_prefetched' with linespoints, '' using 2:16 title 'optimised\_yunus\_threaded' with linespoints, '' using 2:18 title 'optimised\_berk\_openmp' with linespoints"
gnuplot -e "set terminal png size 1280,720; set output 'graphs/results2_optimised.png'; plot 'results2' using 2:10 title 'optimised\_berk' with linespoints, '' using 2:12 title 'optimised\_yunus' with linespoints, '' using 2:14 title 'optimised\_otto\_prefetched' with linespoints, '' using 2:16 title 'optimised\_yunus\_threaded' with linespoints, '' using 2:18 title 'optimised\_berk\_openmp' with linespoints"

gnuplot -e "set terminal png size 1280,720; set output 'graphs/results3_all.png'; plot 'results3' using 2:8 title 'simple' with linespoints, '' using 2:10 title 'optimised\_berk' with linespoints, '' using 2:12 title 'optimised\_yunus' with linespoints, '' using 2:14 title 'optimised\_otto\_prefetched' with linespoints, '' using 2:16 title 'optimised\_yunus\_threaded' with linespoints, '' using 2:18 title 'optimised\_berk\_openmp' with linespoints"
gnuplot -e "set terminal png size 1280,720; set output 'graphs/results3_optimised.png'; plot 'results3' using 2:10 title 'optimised\_berk' with linespoints, '' using 2:12 title 'optimised\_yunus' with linespoints, '' using 2:14 title 'optimised\_otto\_prefetched' with linespoints, '' using 2:16 title 'optimised\_yunus\_threaded' with linespoints, '' using 2:18 title 'optimised\_berk\_openmp' with linespoints"

gnuplot -e "set terminal png size 1280,720; set output 'graphs/results4_all.png'; plot 'results4' using 2:8 title 'simple' with linespoints, '' using 2:10 title 'optimised\_berk' with linespoints, '' using 2:12 title 'optimised\_yunus' with linespoints, '' using 2:14 title 'optimised\_otto\_prefetched' with linespoints, '' using 2:16 title 'optimised\_yunus\_threaded' with linespoints, '' using 2:18 title 'optimised\_berk\_openmp' with linespoints"
gnuplot -e "set terminal png size 1280,720; set output 'graphs/results4_optimised.png'; plot 'results4' using 2:10 title 'optimised\_berk' with linespoints, '' using 2:12 title 'optimised\_yunus' with linespoints, '' using 2:14 title 'optimised\_otto\_prefetched' with linespoints, '' using 2:16 title 'optimised\_yunus\_threaded' with linespoints, '' using 2:18 title 'optimised\_berk\_openmp' with linespoints"

gnuplot -e "set terminal png size 1280,720; set output 'graphs/results5_all.png'; plot 'results5' using 2:8 title 'simple' with linespoints, '' using 2:10 title 'optimised\_berk' with linespoints, '' using 2:12 title 'optimised\_yunus' with linespoints, '' using 2:14 title 'optimised\_otto\_prefetched' with linespoints, '' using 2:16 title 'optimised\_yunus\_threaded' with linespoints, '' using 2:18 title 'optimised\_berk\_openmp' with linespoints"
gnuplot -e "set terminal png size 1280,720; set output 'graphs/results5_optimised.png'; plot 'results5' using 2:10 title 'optimised\_berk' with linespoints, '' using 2:12 title 'optimised\_yunus' with linespoints, '' using 2:14 title 'optimised\_otto\_prefetched' with linespoints, '' using 2:16 title 'optimised\_yunus\_threaded' with linespoints, '' using 2:18 title 'optimised\_berk\_openmp' with linespoints"

gnuplot -e "set terminal png size 1280,720; set output 'graphs/results6_all.png'; plot 'results6' using 2:8 title 'simple' with linespoints, '' using 2:10 title 'optimised\_berk' with linespoints, '' using 2:12 title 'optimised\_yunus' with linespoints, '' using 2:14 title 'optimised\_otto\_prefetched' with linespoints, '' using 2:16 title 'optimised\_yunus\_threaded' with linespoints, '' using 2:18 title 'optimised\_berk\_openmp' with linespoints"
gnuplot -e "set terminal png size 1280,720; set output 'graphs/results6_optimised.png'; plot 'results6' using 2:10 title 'optimised\_berk' with linespoints, '' using 2:12 title 'optimised\_yunus' with linespoints, '' using 2:14 title 'optimised\_otto\_prefetched' with linespoints, '' using 2:16 title 'optimised\_yunus\_threaded' with linespoints, '' using 2:18 title 'optimised\_berk\_openmp' with linespoints"

gnuplot -e "set terminal png size 1280,720; set output 'graphs/results7_all.png'; plot 'results7' using 2:8 title 'simple' with linespoints, '' using 2:10 title 'optimised\_berk' with linespoints, '' using 2:12 title 'optimised\_yunus' with linespoints, '' using 2:14 title 'optimised\_otto\_prefetched' with linespoints, '' using 2:16 title 'optimised\_yunus\_threaded' with linespoints, '' using 2:18 title 'optimised\_berk\_openmp' with linespoints"
gnuplot -e "set terminal png size 1280,720; set output 'graphs/results7_optimised.png'; plot 'results7' using 2:10 title 'optimised\_berk' with linespoints, '' using 2:12 title 'optimised\_yunus' with linespoints, '' using 2:14 title 'optimised\_otto\_prefetched' with linespoints, '' using 2:16 title 'optimised\_yunus\_threaded' with linespoints, '' using 2:18 title 'optimised\_berk\_openmp' with linespoints"

gnuplot -e "set terminal png size 1280,720; set output 'graphs/results8_all.png'; plot 'results8' using 2:8 title 'simple' with linespoints, '' using 2:10 title 'optimised\_berk' with linespoints, '' using 2:12 title 'optimised\_yunus' with linespoints, '' using 2:14 title 'optimised\_otto\_prefetched' with linespoints, '' using 2:16 title 'optimised\_yunus\_threaded' with linespoints, '' using 2:18 title 'optimised\_berk\_openmp' with linespoints"
gnuplot -e "set terminal png size 1280,720; set output 'graphs/results8_optimised.png'; plot 'results8' using 2:10 title 'optimised\_berk' with linespoints, '' using 2:12 title 'optimised\_yunus' with linespoints, '' using 2:14 title 'optimised\_otto\_prefetched' with linespoints, '' using 2:16 title 'optimised\_yunus\_threaded' with linespoints, '' using 2:18 title 'optimised\_berk\_openmp' with linespoints"